// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTpFfMmJhFI28ZPTZFmNhpcz1vAm6-N90',
    appId: '1:379570037623:ios:2ee6069a06d7b0b43eb772',
    messagingSenderId: '379570037623',
    projectId: 'wise-sch',
    storageBucket: 'wise-sch.firebasestorage.app',
    iosBundleId: 'com.example.wiseSchool',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFPqo6GLfiVUEnLbtSwL_G7O9S2sqmqp4',
    appId: '1:379570037623:web:1102eb0dd132d3573eb772',
    messagingSenderId: '379570037623',
    projectId: 'wise-sch',
    authDomain: 'wise-sch.firebaseapp.com',
    storageBucket: 'wise-sch.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFPqo6GLfiVUEnLbtSwL_G7O9S2sqmqp4',
    appId: '1:379570037623:web:1102eb0dd132d3573eb772',
    messagingSenderId: '379570037623',
    projectId: 'wise-sch',
    authDomain: 'wise-sch.firebaseapp.com',
    storageBucket: 'wise-sch.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTpFfMmJhFI28ZPTZFmNhpcz1vAm6-N90',
    appId: '1:379570037623:ios:2ee6069a06d7b0b43eb772',
    messagingSenderId: '379570037623',
    projectId: 'wise-sch',
    storageBucket: 'wise-sch.firebasestorage.app',
    iosBundleId: 'com.example.wiseSchool',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChC2FhTOsaMFozkV3g7M6wJVQFIfPJYIE',
    appId: '1:379570037623:android:fe5bc6df1921beba3eb772',
    messagingSenderId: '379570037623',
    projectId: 'wise-sch',
    storageBucket: 'wise-sch.firebasestorage.app',
  );

}